name: Deploy

on:
  push:
    branches:
      - prod

jobs:
  print-message:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Print message
        run: echo "Testing Push"