name: Deploy

on:
  push:
    branches:
      - prod

jobs:
  deploy-docker:
    runs-on: ubuntu-latest
    steps:
      # Step 1: Checkout repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # Step 2: Authenticate with Google Cloud
      - name: Set up Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v2
        with:
          project_id: ridwan-faturrahman
          service_account_key: ${{ secrets.GCP_SA_KEY }}
          export_default_credentials: true

      # Step 3: Build Docker image
      - name: Build Docker image
        run: |
          IMAGE_NAME=us-central1-docker.pkg.dev/ridwan-faturrahman/fastapi-repo/fastapi-app
          IMAGE_TAG=${GITHUB_SHA::7}
          docker build -t $IMAGE_NAME:latest -t $IMAGE_NAME:$IMAGE_TAG .

      # Step 4: Push Docker image
      - name: Push Docker image
        run: |
          IMAGE_NAME=us-central1-docker.pkg.dev/ridwan-faturrahman/fastapi-repo/fastapi-app
          IMAGE_TAG=${GITHUB_SHA::7}
          docker push $IMAGE_NAME:latest
          docker push $IMAGE_NAME:$IMAGE_TAG